// Generated by CIRCT be09da04d
module pc(
  input         clk,
                rst,
                JUMP,
  input  [31:0] JUMP_PC,
  output [31:0] pc
);

  reg [31:0] pc_reg;
  always_ff @(posedge clk) begin
    if (rst)
      pc_reg <= 32'h0;
    else
      pc_reg <= JUMP ? JUMP_PC : pc_reg + 32'h4;
  end // always_ff @(posedge)
  assign pc = pc_reg;
endmodule

module mem(
  input         clk,
  input  [31:0] im_addr,
  input  [2:0]  dm_rd_ctrl,
  input  [1:0]  dm_wr_ctrl,
  input  [31:0] dm_addr,
                dm_din,
  output [31:0] im_dout,
                dm_dout
);

  reg  [31:0]      mem[0:4095];

  initial begin
    $readmemh("./problem/inst.dat", mem);
  end
  wire             _GEN = 1'h0;
  always_ff @(posedge clk) begin
    if (_GEN) begin
    end
    else begin
      if (|dm_wr_ctrl) begin
        automatic logic             _GEN_0 = dm_wr_ctrl == 2'h1;
        automatic logic             _GEN_1 = dm_wr_ctrl == 2'h2;
        automatic logic             _GEN_2 = _GEN_1 & ~(dm_addr[1]);
        automatic logic             _GEN_3 = _GEN_1 & dm_addr[1];
        automatic logic [3:0][31:0] _GEN_4;
        _GEN_4 =
          {{dm_din},
           {{_GEN_3 ? dm_din[15:8] : mem[dm_addr[13:2]][31:24],
             _GEN_3 ? dm_din[7:0] : mem[dm_addr[13:2]][23:16],
             _GEN_2 ? dm_din[15:8] : mem[dm_addr[13:2]][15:8],
             _GEN_2 ? dm_din[7:0] : mem[dm_addr[13:2]][7:0]}},
           {{_GEN_0 & (&(dm_addr[1:0])) ? dm_din[7:0] : mem[dm_addr[13:2]][31:24],
             _GEN_0 & dm_addr[1:0] == 2'h2 ? dm_din[7:0] : mem[dm_addr[13:2]][23:16],
             _GEN_0 & dm_addr[1:0] == 2'h1 ? dm_din[7:0] : mem[dm_addr[13:2]][15:8],
             _GEN_0 & dm_addr[1:0] == 2'h0 ? dm_din[7:0] : mem[dm_addr[13:2]][7:0]}},
           {mem[dm_addr[13:2]]}};
        mem[dm_addr[13:2]] <= _GEN_4[dm_wr_ctrl];
      end
    end
  end // always_ff @(posedge)
  wire [7:0]       _GEN_5 =
    dm_addr[1]
      ? (dm_addr[0] ? mem[dm_addr[13:2]][31:24] : mem[dm_addr[13:2]][23:16])
      : dm_addr[0] ? mem[dm_addr[13:2]][15:8] : mem[dm_addr[13:2]][7:0];
  wire [15:0]      _GEN_6 =
    dm_addr[1] ? mem[dm_addr[13:2]][31:16] : mem[dm_addr[13:2]][15:0];
  wire [7:0][31:0] _GEN_7 =
    {{32'h0},
     {32'h0},
     {mem[dm_addr[13:2]]},
     {{16'h0, _GEN_6}},
     {{{16{_GEN_6[15]}}, _GEN_6}},
     {{24'h0, _GEN_5}},
     {{{24{_GEN_5[7]}}, _GEN_5}},
     {32'h0}};
  assign im_dout = mem[im_addr[13:2]];
  assign dm_dout = _GEN_7[dm_rd_ctrl];
endmodule

module ctrl(
  input  [31:0] inst,
  output        rf_wr_en,
  output [1:0]  rf_wr_sel,
  output        do_jump,
  output [2:0]  BrType,
  output        alu_a_sel,
                alu_b_sel,
  output [3:0]  alu_ctrl,
  output [2:0]  dm_rd_ctrl,
  output [1:0]  dm_wr_ctrl
);

  wire            _GEN = inst[6:0] == 7'h3;
  wire            _GEN_0 = inst[6:0] == 7'h13;
  wire            _GEN_1 = inst[6:0] == 7'h17;
  wire            _GEN_2 = inst[6:0] == 7'h23;
  wire            _GEN_3 = inst[6:0] == 7'h33;
  wire            _GEN_4 = inst[6:0] == 7'h37;
  wire            _GEN_5 = inst[6:0] == 7'h63;
  wire            _GEN_6 = inst[6:0] == 7'h67;
  wire            _GEN_7 = inst[6:0] == 7'h6F;
  wire            _GEN_8 = inst[14:12] == 3'h0;
  wire            _GEN_9 = inst[14:12] == 3'h1;
  wire            _GEN_10 = inst[14:12] == 3'h2;
  wire            _GEN_11 = inst[14:12] == 3'h4;
  wire            _GEN_12 = inst[14:12] == 3'h5;
  wire            _GEN_13 = _GEN_7 | _GEN_6;
  wire            _GEN_14 = _GEN_1 | _GEN_0 | _GEN_3;
  wire [3:0]      _GEN_15 = {inst[30], 3'h5};
  wire [3:0]      _GEN_16 = {3'h0, _GEN_9};
  wire [7:0][3:0] _GEN_17 =
    {{4'h7}, {4'h6}, {_GEN_15}, {4'h4}, {4'h3}, {4'h2}, {_GEN_16}, {_GEN_16}};
  wire [7:0][3:0] _GEN_18 =
    {{4'h7},
     {4'h6},
     {_GEN_15},
     {4'h4},
     {4'h3},
     {4'h2},
     {4'h1},
     {{~(~_GEN_8 | ~(inst[30])), 3'h0}}};
  assign rf_wr_en = _GEN_4 | _GEN_1 | _GEN_7 | _GEN_6 | _GEN | _GEN_0 | _GEN_3;
  assign rf_wr_sel = _GEN ? 2'h3 : _GEN_14 ? 2'h2 : {1'h0, _GEN_13};
  assign do_jump = _GEN_13;
  assign BrType =
    _GEN_5 & (&(inst[14:12]))
      ? 3'h6
      : _GEN_5 & inst[14:12] == 3'h6
          ? 3'h5
          : _GEN_5 & _GEN_12
              ? 3'h4
              : _GEN_5 & _GEN_11
                  ? 3'h3
                  : _GEN_5 & _GEN_9 ? 3'h2 : {2'h0, _GEN_5 & _GEN_8};
  assign alu_a_sel = _GEN_2 | _GEN_0 | _GEN_6 | _GEN | _GEN_3;
  assign alu_b_sel = _GEN_4 | _GEN_1 | _GEN_7 | _GEN_6 | _GEN_5 | _GEN | _GEN_2 | _GEN_0;
  assign alu_ctrl =
    _GEN_14
      ? (_GEN_3 ? _GEN_18[inst[14:12]] : _GEN_0 ? _GEN_17[inst[14:12]] : 4'h0)
      : 4'h0;
  assign dm_rd_ctrl =
    _GEN & _GEN_12
      ? 3'h4
      : _GEN & _GEN_11
          ? 3'h2
          : _GEN & _GEN_10 ? 3'h5 : _GEN & _GEN_9 ? 3'h3 : {2'h0, _GEN & _GEN_8};
  assign dm_wr_ctrl =
    _GEN_2 & _GEN_10 ? 2'h3 : _GEN_2 & _GEN_9 ? 2'h2 : {1'h0, _GEN_2 & _GEN_8};
endmodule

module imm(
  input  [31:0] inst,
  output [31:0] out
);

  wire [19:0] _GEN = {20{inst[31]}};
  assign out =
    inst[6:0] == 7'h6F
      ? {{12{inst[31]}}, inst[19:12], inst[20], inst[30:21], 1'h0}
      : inst[6:0] == 7'h37 | inst[6:0] == 7'h17
          ? {inst[31:12], 12'h0}
          : inst[6:0] == 7'h63
              ? {_GEN, inst[7], inst[30:25], inst[11:8], 1'h0}
              : inst[6:0] == 7'h23
                  ? {_GEN, inst[31:25], inst[11:7]}
                  : inst[6:0] == 7'h3 | inst[6:0] == 7'h13 | inst[6:0] == 7'h67
                      ? {_GEN, inst[31:20]}
                      : 32'h0;
endmodule

module reg_file(
  input         clk,
                rst,
  input  [4:0]  A1,
                A2,
                A3,
  input  [31:0] WD,
  input         WE,
  output [31:0] RD1,
                RD2
);

  reg [31:0] reg_file[0:31];
  always_ff @(posedge clk) begin
    if (rst) begin
    end
    else begin
      if (WE & (|A3))
        reg_file[A3] <= WD;
    end
  end // always_ff @(posedge)
  assign RD1 = A1 == 5'h0 ? 32'h0 : reg_file[A1];
  assign RD2 = A2 == 5'h0 ? 32'h0 : reg_file[A2];
endmodule

module branch(
  input  [31:0] REG1,
                REG2,
  input  [2:0]  Type,
  output        BrE
);

  assign BrE =
    Type == 3'h1 & REG1 == REG2 | Type == 3'h2 & REG1 != REG2 | Type == 3'h3
    & $signed(REG1) < $signed(REG2) | Type == 3'h4 & $signed(REG1) >= $signed(REG2)
    | Type == 3'h5 & REG1 < REG2 | Type == 3'h6 & REG1 >= REG2;
endmodule

module alu(
  input  [31:0] SrcA,
                SrcB,
  input  [3:0]  func,
  output [31:0] ALUout
);

  wire [31:0]       _GEN = {27'h0, SrcB[4:0]};
  wire [15:0][31:0] _GEN_0 =
    {{32'h0},
     {SrcB},
     {$signed($signed(SrcA) >>> _GEN)},
     {32'h0},
     {32'h0},
     {32'h0},
     {32'h0},
     {SrcA - SrcB},
     {SrcA & SrcB},
     {SrcA | SrcB},
     {SrcA >> _GEN},
     {SrcA ^ SrcB},
     {{31'h0, SrcA < SrcB}},
     {{31'h0, $signed(SrcA) < $signed(SrcB)}},
     {SrcA << _GEN},
     {SrcA + SrcB}};
  assign ALUout = _GEN_0[func];
endmodule

module CPU(
  input clk,
        rst
);

  wire [31:0]      _reg_file0_RD1;
  wire [31:0]      _reg_file0_RD2;
  wire [31:0]      _mem0_im_dout;
  wire [31:0]      _mem0_dm_dout;
  wire [31:0]      _pc0_pc;
  wire [31:0]      _alu0_ALUout;
  wire             _branch0_BrE;
  wire [31:0]      _imm0_out;
  wire             _ctrl0_rf_wr_en;
  wire [1:0]       _ctrl0_rf_wr_sel;
  wire             _ctrl0_do_jump;
  wire [2:0]       _ctrl0_BrType;
  wire             _ctrl0_alu_a_sel;
  wire             _ctrl0_alu_b_sel;
  wire [3:0]       _ctrl0_alu_ctrl;
  wire [2:0]       _ctrl0_dm_rd_ctrl;
  wire [1:0]       _ctrl0_dm_wr_ctrl;
  wire [3:0][31:0] _GEN =
    {{_mem0_dm_dout}, {_alu0_ALUout}, {_pc0_pc + 32'h4}, {_imm0_out}};
  ctrl ctrl0 (
    .inst       (_mem0_im_dout),
    .rf_wr_en   (_ctrl0_rf_wr_en),
    .rf_wr_sel  (_ctrl0_rf_wr_sel),
    .do_jump    (_ctrl0_do_jump),
    .BrType     (_ctrl0_BrType),
    .alu_a_sel  (_ctrl0_alu_a_sel),
    .alu_b_sel  (_ctrl0_alu_b_sel),
    .alu_ctrl   (_ctrl0_alu_ctrl),
    .dm_rd_ctrl (_ctrl0_dm_rd_ctrl),
    .dm_wr_ctrl (_ctrl0_dm_wr_ctrl)
  );
  imm imm0 (
    .inst (_mem0_im_dout),
    .out  (_imm0_out)
  );
  branch branch0 (
    .REG1 (_reg_file0_RD1),
    .REG2 (_reg_file0_RD2),
    .Type (_ctrl0_BrType),
    .BrE  (_branch0_BrE)
  );
  alu alu0 (
    .SrcA   (_ctrl0_alu_a_sel ? _reg_file0_RD1 : _pc0_pc),
    .SrcB   (_ctrl0_alu_b_sel ? _imm0_out : _reg_file0_RD2),
    .func   (_ctrl0_alu_ctrl),
    .ALUout (_alu0_ALUout)
  );
  pc pc0 (
    .clk     (clk),
    .rst     (rst),
    .JUMP    (_branch0_BrE | _ctrl0_do_jump),
    .JUMP_PC (_mem0_im_dout[6:0] == 7'h67 ? {_alu0_ALUout[31:1], 1'h0} : _alu0_ALUout),
    .pc      (_pc0_pc)
  );
  mem mem0 (
    .clk        (clk),
    .im_addr    (_pc0_pc),
    .dm_rd_ctrl (_ctrl0_dm_rd_ctrl),
    .dm_wr_ctrl (_ctrl0_dm_wr_ctrl),
    .dm_addr    (_alu0_ALUout),
    .dm_din     (_reg_file0_RD2),
    .im_dout    (_mem0_im_dout),
    .dm_dout    (_mem0_dm_dout)
  );
  reg_file reg_file0 (
    .clk (clk),
    .rst (rst),
    .A1  (_mem0_im_dout[19:15]),
    .A2  (_mem0_im_dout[24:20]),
    .A3  (_mem0_im_dout[11:7]),
    .WD  (_GEN[_ctrl0_rf_wr_sel]),
    .WE  (_ctrl0_rf_wr_en),
    .RD1 (_reg_file0_RD1),
    .RD2 (_reg_file0_RD2)
  );
endmodule

